### ISSUE TITLE
Re-running Munki-Enroll Script Causes an Additional Subdirectory to be Created 

### ISSUE THREAD

**Issue by KLEPTOROTH** [edingc/munki-enroll#18]
Hello there,
I'm running into an issue where, if I run munki_enroll.sh once, it creates the manifest as follows:

clients/computername

When I run it a second time, it makes:
clients/clients/computername
And a third:
clients/clients/clients/computername
And so on.

My understanding is that if you run it a second time, it should check to see if clients/computername exists, and to quit if it does.  However this doesn't happen.

Anyone else seeing this behavior?

**Comment by KLEPTOROTH** [comment]
Think I figured out the cause of the issue at least:
`if [ $( echo "$IDENTIFIER" | grep "/" ) ]
	    then
	    IDENTIFIER_PATH=$( echo "$IDENTIFIER" | sed 's/\/[^/]*$//' ); 
	    defaults write /Library/Preferences/ManagedInstalls ClientIdentifier "'$IDENTIFIER_PATH/clients/$HOSTNAME'"`

`if [ $( echo "$IDENTIFIER" | grep "/" ) ]` causes ANY output containing a / to pass the script to the then statement of `IDENTIFIER_PATH=$( echo "$IDENTIFIER" | sed 's/\/[^/]*$//' );` 

So if you run it on a computer where the script has already been run, and the $IDENTIFIER is clients/computername, it returns output due to the `grep "/"` match.  this causes `defaults write /Library/Preferences/ManagedInstalls ClientIdentifier "'$IDENTIFIER_PATH/clients/$HOSTNAME'"` to write clients/clients/computername, and adding an additional clients/ subdirectory every time the script is run.

**Comment by edingc** [comment]
This is expected behavior based on how munki_enroll.sh is currently written. It is assumed that the script will not run more than once on each machine. This is because the environment in which the script was developed relied only on munki-enroll during initial imaging through DeployStudio.

I'm going to mark this as a "wont-fix" because a solution to this is going to be largely environment dependent. My suggestion would be to modify munki_enroll.sh to set something on the client to signal that it has been run, and then add a check within the script to look for whatever was set.
